"""Initial_tables

Revision ID: 6ef3e4f64513
Revises: 
Create Date: 2026-02-19 17:35:46.432531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef3e4f64513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_code', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('team_color', sa.String(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_driver_race_code', 'drivers', ['race_id', 'driver_code'], unique=False)
    op.create_index(op.f('ix_drivers_driver_code'), 'drivers', ['driver_code'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('track_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('point_index', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('s', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('s1', sa.Float(), nullable=True),
    sa.Column('s2', sa.Float(), nullable=True),
    sa.Column('s3', sa.Float(), nullable=True),
    sa.Column('lap_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('enter_time', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('t', sa.Float(), nullable=True),
    sa.Column('s', sa.Float(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_driver_s', 'positions', ['driver_id', 's'], unique=False)
    op.create_index('idx_positions_driver_t', 'positions', ['driver_id', 't'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('t', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('drs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_driver_t', 'telemetry', ['driver_id', 't'], unique=False)
    op.create_index('idx_race_season_round', 'races', ['season', 'round'], unique=True)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_index('idx_race_season_round', table_name='races')
    op.drop_index('idx_telemetry_driver_t', table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index('idx_positions_driver_t', table_name='positions')
    op.drop_index('idx_positions_driver_s', table_name='positions')
    op.drop_table('positions')
    op.drop_table('pit_stops')
    op.drop_table('laps')
    op.drop_table('track_points')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_driver_code'), table_name='drivers')
    op.drop_index('idx_driver_race_code', table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
